"""Shared domain type aliases.

Strongly-typed, string-backed identifiers for the major aggregate roots.  Using
``NewType`` makes it impossible to accidentally pass a ``ConversationId`` where
a ``UserId`` is expected — mypy/pyright will catch the mismatch at check time.

Usage::

    from domains.shared.types import UserId, ConversationId

    async def get_conversations(user_id: UserId) -> list[Conversation]:
        ...

Notes
-----
* These are *type-level* aliases.  At runtime they are plain :class:`str`
  values (``NewType`` has zero runtime overhead).
* Domain services and repositories should annotate IDs with these types instead
  of bare ``str`` to improve call-site clarity.
* IDs are prefixed string identifiers (e.g. ``usr_…``) generated by
  :mod:`core.ids`; SQLAlchemy ORM models use plain ``str`` columns.
"""

from __future__ import annotations

from typing import NewType

# ---------------------------------------------------------------------------
# Aggregate identity types
# ---------------------------------------------------------------------------

#: Identity of a :class:`~app.domains.auth.models.User` aggregate.
UserId = NewType("UserId", str)

#: Identity of a :class:`~app.domains.auth.models.Role`.
RoleId = NewType("RoleId", str)

#: Identity of a :class:`~app.domains.auth.models.Permission`.
PermissionId = NewType("PermissionId", str)


#: Identity of a :class:`~app.domains.chat.models.Conversation` aggregate.
ConversationId = NewType("ConversationId", str)

#: Identity of a :class:`~app.domains.chat.models.Message`.
MessageId = NewType("MessageId", str)


# ---------------------------------------------------------------------------
# Primitive value-type aliases
# ---------------------------------------------------------------------------

#: A permission key string, e.g. ``"chat:write"``, ``"admin:users"``.
PermissionKey = NewType("PermissionKey", str)

#: OAuth provider name, e.g. ``"google"``, ``"kakao"``, ``"naver"``.
OAuthProvider = NewType("OAuthProvider", str)

#: JWT ID claim — uniquely identifies a token for blacklisting.
JtiStr = NewType("JtiStr", str)
