// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ChatMessage
 *
 * A single message in a conversation turn.
 *
 * Attributes
 * ----------
 * role:
 * Speaker role — ``"user"``, ``"assistant"``, or ``"system"``.
 * Unknown roles default to ``HumanMessage``.
 * content:
 * Text content of the message.
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 *
 * Request body for chat endpoints.
 *
 * Attributes
 * ----------
 * messages:
 * Ordered conversation history.  Must contain at least one message.
 * system:
 * Optional system prompt prepended before all other messages.
 * Equivalent to adding a ``{"role": "system", ...}`` entry at the front.
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * System
     */
    system?: string | null;
};

/**
 * ChatResponse
 *
 * Response body for the non-streaming ``/complete`` endpoint.
 *
 * Attributes
 * ----------
 * content:
 * The model's full reply text.
 * model:
 * Active LiteLLM model identifier, e.g. ``"openai/gpt-4o-mini"``.
 * Included for debugging and provider-routing verification.
 */
export type ChatResponse = {
    /**
     * Content
     */
    content: string;
    /**
     * Model
     */
    model?: string | null;
};

/**
 * ConversationCreate
 *
 * Request body for POST /chat/conversations.
 */
export type ConversationCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * Model Name
     */
    model_name: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * EmploymentTypeCreate
 *
 * Request body for POST /employment-types.
 */
export type EmploymentTypeCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * EmploymentTypeResponse
 *
 * Single employment-type response body.
 */
export type EmploymentTypeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * GradeCreate
 *
 * Request body for POST /grades.
 */
export type GradeCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
    /**
     * Bg
     */
    bg: string;
    /**
     * Border
     */
    border: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * GradeReorder
 *
 * Request body for PATCH /grades/order — full ordered list of ids (low→high).
 */
export type GradeReorder = {
    /**
     * Ordered Ids
     */
    ordered_ids: Array<string>;
};

/**
 * GradeResponse
 *
 * Single grade response body.
 */
export type GradeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
    /**
     * Bg
     */
    bg: string;
    /**
     * Border
     */
    border: string;
    /**
     * Description
     */
    description: string;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * GradeUpdate
 *
 * Request body for PATCH /grades/{id} — partial (rename + meta).
 */
export type GradeUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Bg
     */
    bg?: string | null;
    /**
     * Border
     */
    border?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 *
 * Request body for POST /auth/login.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LogoutRequest
 *
 * Request body for POST /auth/logout.
 */
export type LogoutRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * MemberCreate
 *
 * Request body for POST /members. ``employee_no`` is server-generated.
 */
export type MemberCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Department
     */
    department: string;
    /**
     * Rank
     */
    rank: string;
    /**
     * Grade
     */
    grade: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Email
     */
    email: string;
};

/**
 * MemberListResponse
 *
 * Paginated list envelope for GET /members.
 */
export type MemberListResponse = {
    /**
     * Items
     */
    items: Array<MemberResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * MemberResponse
 *
 * Single-member response body.
 */
export type MemberResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Employee No
     */
    employee_no: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Department
     */
    department: string;
    /**
     * Rank
     */
    rank: string;
    /**
     * Grade
     */
    grade: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MemberStatsResponse
 *
 * Summary statistics for the dashboard cards (active members only).
 */
export type MemberStatsResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Department Count
     */
    department_count: number;
    /**
     * New This Month
     */
    new_this_month: number;
    /**
     * Grade Distribution
     */
    grade_distribution: {
        [key: string]: number;
    };
    /**
     * Departments
     */
    departments: Array<string>;
};

/**
 * MemberUpdate
 *
 * Request body for PATCH /members/{id}. All fields optional (partial update).
 */
export type MemberUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Rank
     */
    rank?: string | null;
    /**
     * Grade
     */
    grade?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Token Count
     */
    token_count: number | null;
    /**
     * Finish Reason
     */
    finish_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * OAuthLoginURLResponse
 *
 * Response body for GET /auth/oauth/{provider}/login.
 */
export type OAuthLoginUrlResponse = {
    /**
     * Authorization Url
     */
    authorization_url: string;
    /**
     * State
     */
    state: string;
};

/**
 * PasswordResetConfirmRequest
 *
 * Request body for POST /auth/password-reset/confirm.
 */
export type PasswordResetConfirmRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PasswordResetConfirmResponse
 *
 * Response body for POST /auth/password-reset/confirm.
 */
export type PasswordResetConfirmResponse = {
    /**
     * Message
     */
    message?: string;
};

/**
 * PasswordResetRequest
 *
 * Request body for POST /auth/password-reset (request reset link).
 */
export type PasswordResetRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordResetRequestResponse
 *
 * Response body for POST /auth/password-reset.
 *
 * The message is intentionally generic to prevent account enumeration.
 */
export type PasswordResetRequestResponse = {
    /**
     * Message
     */
    message?: string;
};

/**
 * PositionCreate
 *
 * Request body for POST /positions.
 */
export type PositionCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * PositionReorder
 *
 * Request body for PATCH /positions/order — full ordered list of ids (low→high).
 */
export type PositionReorder = {
    /**
     * Ordered Ids
     */
    ordered_ids: Array<string>;
};

/**
 * PositionResponse
 *
 * Single-position response body.
 */
export type PositionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * PositionUpdate
 *
 * Request body for PATCH /positions/{id} (rename).
 */
export type PositionUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ProviderInfoResponse
 *
 * Response body for the ``/provider`` info endpoint.
 *
 * Attributes
 * ----------
 * provider:
 * Active provider name, e.g. ``"openai"``, ``"ollama"``.
 * model:
 * Base model name, e.g. ``"gpt-4o-mini"``, ``"llama3.2"``.
 * litellm_model:
 * Full LiteLLM model identifier, e.g. ``"openai/gpt-4o-mini"``.
 */
export type ProviderInfoResponse = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Litellm Model
     */
    litellm_model: string;
};

/**
 * RefreshRequest
 *
 * Request body for POST /auth/refresh.
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * SendMessageRequest
 *
 * Request body for POST /chat/conversations/{id}/messages.
 */
export type SendMessageRequest = {
    /**
     * Content
     */
    content: string;
    /**
     * Stream
     *
     * When True, response is SSE-streamed. When False, returns full JSON.
     */
    stream?: boolean;
};

/**
 * SignupRequest
 *
 * Request body for POST /auth/signup.
 */
export type SignupRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * SignupResponse
 *
 * Response body for POST /auth/signup.
 */
export type SignupResponse = {
    user: UserResponse;
    /**
     * Message
     */
    message?: string;
};

/**
 * TokenResponse
 *
 * JWT pair returned by login and refresh endpoints.
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
    /**
     * Expires In
     *
     * Access token TTL in seconds.
     */
    expires_in: number;
};

/**
 * UserResponse
 *
 * Public user representation — never includes hashed_password.
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyEmailResponse
 *
 * Response body for POST /auth/verify-email/{token}.
 */
export type VerifyEmailResponse = {
    /**
     * Message
     */
    message?: string;
    user: UserResponse;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Response Ready Ready Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadyReadyGetResponse = ReadyReadyGetResponses[keyof ReadyReadyGetResponses];

export type SignupApiV1AuthSignupPostData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup';
};

export type SignupApiV1AuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupApiV1AuthSignupPostError = SignupApiV1AuthSignupPostErrors[keyof SignupApiV1AuthSignupPostErrors];

export type SignupApiV1AuthSignupPostResponses = {
    /**
     * Successful Response
     */
    201: SignupResponse;
};

export type SignupApiV1AuthSignupPostResponse = SignupApiV1AuthSignupPostResponses[keyof SignupApiV1AuthSignupPostResponses];

export type VerifyEmailApiV1AuthVerifyEmailTokenPostData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/auth/verify-email/{token}';
};

export type VerifyEmailApiV1AuthVerifyEmailTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailApiV1AuthVerifyEmailTokenPostError = VerifyEmailApiV1AuthVerifyEmailTokenPostErrors[keyof VerifyEmailApiV1AuthVerifyEmailTokenPostErrors];

export type VerifyEmailApiV1AuthVerifyEmailTokenPostResponses = {
    /**
     * Successful Response
     */
    200: VerifyEmailResponse;
};

export type VerifyEmailApiV1AuthVerifyEmailTokenPostResponse = VerifyEmailApiV1AuthVerifyEmailTokenPostResponses[keyof VerifyEmailApiV1AuthVerifyEmailTokenPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body: LogoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type RequestPasswordResetApiV1AuthPasswordResetPostData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset';
};

export type RequestPasswordResetApiV1AuthPasswordResetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestPasswordResetApiV1AuthPasswordResetPostError = RequestPasswordResetApiV1AuthPasswordResetPostErrors[keyof RequestPasswordResetApiV1AuthPasswordResetPostErrors];

export type RequestPasswordResetApiV1AuthPasswordResetPostResponses = {
    /**
     * Successful Response
     */
    202: PasswordResetRequestResponse;
};

export type RequestPasswordResetApiV1AuthPasswordResetPostResponse = RequestPasswordResetApiV1AuthPasswordResetPostResponses[keyof RequestPasswordResetApiV1AuthPasswordResetPostResponses];

export type ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostData = {
    body: PasswordResetConfirmRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset/confirm';
};

export type ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostError = ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostErrors[keyof ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostErrors];

export type ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostResponses = {
    /**
     * Successful Response
     */
    200: PasswordResetConfirmResponse;
};

export type ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostResponse = ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostResponses[keyof ConfirmPasswordResetApiV1AuthPasswordResetConfirmPostResponses];

export type GetMeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetMeApiV1AuthMeGetResponse = GetMeApiV1AuthMeGetResponses[keyof GetMeApiV1AuthMeGetResponses];

export type OauthLoginApiV1AuthOauthProviderLoginGetData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/oauth/{provider}/login';
};

export type OauthLoginApiV1AuthOauthProviderLoginGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthLoginApiV1AuthOauthProviderLoginGetError = OauthLoginApiV1AuthOauthProviderLoginGetErrors[keyof OauthLoginApiV1AuthOauthProviderLoginGetErrors];

export type OauthLoginApiV1AuthOauthProviderLoginGetResponses = {
    /**
     * Successful Response
     */
    200: OAuthLoginUrlResponse;
};

export type OauthLoginApiV1AuthOauthProviderLoginGetResponse = OauthLoginApiV1AuthOauthProviderLoginGetResponses[keyof OauthLoginApiV1AuthOauthProviderLoginGetResponses];

export type OauthCallbackApiV1AuthOauthProviderCallbackGetData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query: {
        /**
         * Code
         *
         * Authorization code from provider
         */
        code: string;
        /**
         * State
         *
         * CSRF state nonce
         */
        state: string;
    };
    url: '/api/v1/auth/oauth/{provider}/callback';
};

export type OauthCallbackApiV1AuthOauthProviderCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthCallbackApiV1AuthOauthProviderCallbackGetError = OauthCallbackApiV1AuthOauthProviderCallbackGetErrors[keyof OauthCallbackApiV1AuthOauthProviderCallbackGetErrors];

export type OauthCallbackApiV1AuthOauthProviderCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatCompleteApiV1ChatCompletePostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/complete';
};

export type ChatCompleteApiV1ChatCompletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatCompleteApiV1ChatCompletePostError = ChatCompleteApiV1ChatCompletePostErrors[keyof ChatCompleteApiV1ChatCompletePostErrors];

export type ChatCompleteApiV1ChatCompletePostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatCompleteApiV1ChatCompletePostResponse = ChatCompleteApiV1ChatCompletePostResponses[keyof ChatCompleteApiV1ChatCompletePostResponses];

export type ChatStreamApiV1ChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/stream';
};

export type ChatStreamApiV1ChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiV1ChatStreamPostError = ChatStreamApiV1ChatStreamPostErrors[keyof ChatStreamApiV1ChatStreamPostErrors];

export type ChatStreamApiV1ChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProviderInfoApiV1ChatProviderGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/provider';
};

export type GetProviderInfoApiV1ChatProviderGetResponses = {
    /**
     * Successful Response
     */
    200: ProviderInfoResponse;
};

export type GetProviderInfoApiV1ChatProviderGetResponse = GetProviderInfoApiV1ChatProviderGetResponses[keyof GetProviderInfoApiV1ChatProviderGetResponses];

export type ListConversationsApiV1ChatConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/conversations';
};

export type ListConversationsApiV1ChatConversationsGetResponses = {
    /**
     * Response List Conversations Api V1 Chat Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationResponse>;
};

export type ListConversationsApiV1ChatConversationsGetResponse = ListConversationsApiV1ChatConversationsGetResponses[keyof ListConversationsApiV1ChatConversationsGetResponses];

export type CreateConversationApiV1ChatConversationsPostData = {
    body: ConversationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/chat/conversations';
};

export type CreateConversationApiV1ChatConversationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationApiV1ChatConversationsPostError = CreateConversationApiV1ChatConversationsPostErrors[keyof CreateConversationApiV1ChatConversationsPostErrors];

export type CreateConversationApiV1ChatConversationsPostResponses = {
    /**
     * Successful Response
     */
    201: ConversationResponse;
};

export type CreateConversationApiV1ChatConversationsPostResponse = CreateConversationApiV1ChatConversationsPostResponses[keyof CreateConversationApiV1ChatConversationsPostResponses];

export type GetConversationApiV1ChatConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{conversation_id}';
};

export type GetConversationApiV1ChatConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1ChatConversationsConversationIdGetError = GetConversationApiV1ChatConversationsConversationIdGetErrors[keyof GetConversationApiV1ChatConversationsConversationIdGetErrors];

export type GetConversationApiV1ChatConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type GetConversationApiV1ChatConversationsConversationIdGetResponse = GetConversationApiV1ChatConversationsConversationIdGetResponses[keyof GetConversationApiV1ChatConversationsConversationIdGetResponses];

export type ListMessagesApiV1ChatConversationsConversationIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{conversation_id}/messages';
};

export type ListMessagesApiV1ChatConversationsConversationIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesApiV1ChatConversationsConversationIdMessagesGetError = ListMessagesApiV1ChatConversationsConversationIdMessagesGetErrors[keyof ListMessagesApiV1ChatConversationsConversationIdMessagesGetErrors];

export type ListMessagesApiV1ChatConversationsConversationIdMessagesGetResponses = {
    /**
     * Response List Messages Api V1 Chat Conversations  Conversation Id  Messages Get
     *
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type ListMessagesApiV1ChatConversationsConversationIdMessagesGetResponse = ListMessagesApiV1ChatConversationsConversationIdMessagesGetResponses[keyof ListMessagesApiV1ChatConversationsConversationIdMessagesGetResponses];

export type SendMessageApiV1ChatConversationsConversationIdMessagesPostData = {
    body: SendMessageRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{conversation_id}/messages';
};

export type SendMessageApiV1ChatConversationsConversationIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageApiV1ChatConversationsConversationIdMessagesPostError = SendMessageApiV1ChatConversationsConversationIdMessagesPostErrors[keyof SendMessageApiV1ChatConversationsConversationIdMessagesPostErrors];

export type SendMessageApiV1ChatConversationsConversationIdMessagesPostResponses = {
    /**
     * Response Send Message Api V1 Chat Conversations  Conversation Id  Messages Post
     *
     * Successful Response
     */
    200: unknown;
};

export type ListMembersApiV1MembersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         *
         * 검색어 — 이름/사번/소속/직급/이메일/연락처 부분일치
         */
        q?: string | null;
        /**
         * Department
         */
        department?: string | null;
        /**
         * Grade
         */
        grade?: string | null;
        /**
         * Sort
         */
        sort?: 'no' | 'name' | 'dept' | 'rank' | 'grade';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/members';
};

export type ListMembersApiV1MembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMembersApiV1MembersGetError = ListMembersApiV1MembersGetErrors[keyof ListMembersApiV1MembersGetErrors];

export type ListMembersApiV1MembersGetResponses = {
    /**
     * Successful Response
     */
    200: MemberListResponse;
};

export type ListMembersApiV1MembersGetResponse = ListMembersApiV1MembersGetResponses[keyof ListMembersApiV1MembersGetResponses];

export type CreateMemberApiV1MembersPostData = {
    body: MemberCreate;
    path?: never;
    query?: never;
    url: '/api/v1/members';
};

export type CreateMemberApiV1MembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMemberApiV1MembersPostError = CreateMemberApiV1MembersPostErrors[keyof CreateMemberApiV1MembersPostErrors];

export type CreateMemberApiV1MembersPostResponses = {
    /**
     * Successful Response
     */
    201: MemberResponse;
};

export type CreateMemberApiV1MembersPostResponse = CreateMemberApiV1MembersPostResponses[keyof CreateMemberApiV1MembersPostResponses];

export type MemberStatsApiV1MembersStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/members/stats';
};

export type MemberStatsApiV1MembersStatsGetResponses = {
    /**
     * Successful Response
     */
    200: MemberStatsResponse;
};

export type MemberStatsApiV1MembersStatsGetResponse = MemberStatsApiV1MembersStatsGetResponses[keyof MemberStatsApiV1MembersStatsGetResponses];

export type MyMemberApiV1MembersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/members/me';
};

export type MyMemberApiV1MembersMeGetResponses = {
    /**
     * Successful Response
     */
    200: MemberResponse;
};

export type MyMemberApiV1MembersMeGetResponse = MyMemberApiV1MembersMeGetResponses[keyof MyMemberApiV1MembersMeGetResponses];

export type ExportMembersApiV1MembersExportGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Department
         */
        department?: string | null;
        /**
         * Grade
         */
        grade?: string | null;
        /**
         * Sort
         */
        sort?: 'no' | 'name' | 'dept' | 'rank' | 'grade';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
    };
    url: '/api/v1/members/export';
};

export type ExportMembersApiV1MembersExportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportMembersApiV1MembersExportGetError = ExportMembersApiV1MembersExportGetErrors[keyof ExportMembersApiV1MembersExportGetErrors];

export type ExportMembersApiV1MembersExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteMemberApiV1MembersMemberIdDeleteData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/members/{member_id}';
};

export type DeleteMemberApiV1MembersMemberIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMemberApiV1MembersMemberIdDeleteError = DeleteMemberApiV1MembersMemberIdDeleteErrors[keyof DeleteMemberApiV1MembersMemberIdDeleteErrors];

export type DeleteMemberApiV1MembersMemberIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMemberApiV1MembersMemberIdDeleteResponse = DeleteMemberApiV1MembersMemberIdDeleteResponses[keyof DeleteMemberApiV1MembersMemberIdDeleteResponses];

export type GetMemberApiV1MembersMemberIdGetData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/members/{member_id}';
};

export type GetMemberApiV1MembersMemberIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMemberApiV1MembersMemberIdGetError = GetMemberApiV1MembersMemberIdGetErrors[keyof GetMemberApiV1MembersMemberIdGetErrors];

export type GetMemberApiV1MembersMemberIdGetResponses = {
    /**
     * Successful Response
     */
    200: MemberResponse;
};

export type GetMemberApiV1MembersMemberIdGetResponse = GetMemberApiV1MembersMemberIdGetResponses[keyof GetMemberApiV1MembersMemberIdGetResponses];

export type UpdateMemberApiV1MembersMemberIdPatchData = {
    body: MemberUpdate;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/members/{member_id}';
};

export type UpdateMemberApiV1MembersMemberIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMemberApiV1MembersMemberIdPatchError = UpdateMemberApiV1MembersMemberIdPatchErrors[keyof UpdateMemberApiV1MembersMemberIdPatchErrors];

export type UpdateMemberApiV1MembersMemberIdPatchResponses = {
    /**
     * Successful Response
     */
    200: MemberResponse;
};

export type UpdateMemberApiV1MembersMemberIdPatchResponse = UpdateMemberApiV1MembersMemberIdPatchResponses[keyof UpdateMemberApiV1MembersMemberIdPatchResponses];

export type ListPositionsApiV1PositionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/positions';
};

export type ListPositionsApiV1PositionsGetResponses = {
    /**
     * Response List Positions Api V1 Positions Get
     *
     * Successful Response
     */
    200: Array<PositionResponse>;
};

export type ListPositionsApiV1PositionsGetResponse = ListPositionsApiV1PositionsGetResponses[keyof ListPositionsApiV1PositionsGetResponses];

export type CreatePositionApiV1PositionsPostData = {
    body: PositionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/positions';
};

export type CreatePositionApiV1PositionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePositionApiV1PositionsPostError = CreatePositionApiV1PositionsPostErrors[keyof CreatePositionApiV1PositionsPostErrors];

export type CreatePositionApiV1PositionsPostResponses = {
    /**
     * Successful Response
     */
    201: PositionResponse;
};

export type CreatePositionApiV1PositionsPostResponse = CreatePositionApiV1PositionsPostResponses[keyof CreatePositionApiV1PositionsPostResponses];

export type ReorderPositionsApiV1PositionsOrderPatchData = {
    body: PositionReorder;
    path?: never;
    query?: never;
    url: '/api/v1/positions/order';
};

export type ReorderPositionsApiV1PositionsOrderPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderPositionsApiV1PositionsOrderPatchError = ReorderPositionsApiV1PositionsOrderPatchErrors[keyof ReorderPositionsApiV1PositionsOrderPatchErrors];

export type ReorderPositionsApiV1PositionsOrderPatchResponses = {
    /**
     * Response Reorder Positions Api V1 Positions Order Patch
     *
     * Successful Response
     */
    200: Array<PositionResponse>;
};

export type ReorderPositionsApiV1PositionsOrderPatchResponse = ReorderPositionsApiV1PositionsOrderPatchResponses[keyof ReorderPositionsApiV1PositionsOrderPatchResponses];

export type DeletePositionApiV1PositionsPositionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type DeletePositionApiV1PositionsPositionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePositionApiV1PositionsPositionIdDeleteError = DeletePositionApiV1PositionsPositionIdDeleteErrors[keyof DeletePositionApiV1PositionsPositionIdDeleteErrors];

export type DeletePositionApiV1PositionsPositionIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePositionApiV1PositionsPositionIdDeleteResponse = DeletePositionApiV1PositionsPositionIdDeleteResponses[keyof DeletePositionApiV1PositionsPositionIdDeleteResponses];

export type RenamePositionApiV1PositionsPositionIdPatchData = {
    body: PositionUpdate;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type RenamePositionApiV1PositionsPositionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenamePositionApiV1PositionsPositionIdPatchError = RenamePositionApiV1PositionsPositionIdPatchErrors[keyof RenamePositionApiV1PositionsPositionIdPatchErrors];

export type RenamePositionApiV1PositionsPositionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PositionResponse;
};

export type RenamePositionApiV1PositionsPositionIdPatchResponse = RenamePositionApiV1PositionsPositionIdPatchResponses[keyof RenamePositionApiV1PositionsPositionIdPatchResponses];

export type ListEmploymentTypesApiV1EmploymentTypesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/employment-types';
};

export type ListEmploymentTypesApiV1EmploymentTypesGetResponses = {
    /**
     * Response List Employment Types Api V1 Employment Types Get
     *
     * Successful Response
     */
    200: Array<EmploymentTypeResponse>;
};

export type ListEmploymentTypesApiV1EmploymentTypesGetResponse = ListEmploymentTypesApiV1EmploymentTypesGetResponses[keyof ListEmploymentTypesApiV1EmploymentTypesGetResponses];

export type CreateEmploymentTypeApiV1EmploymentTypesPostData = {
    body: EmploymentTypeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/employment-types';
};

export type CreateEmploymentTypeApiV1EmploymentTypesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEmploymentTypeApiV1EmploymentTypesPostError = CreateEmploymentTypeApiV1EmploymentTypesPostErrors[keyof CreateEmploymentTypeApiV1EmploymentTypesPostErrors];

export type CreateEmploymentTypeApiV1EmploymentTypesPostResponses = {
    /**
     * Successful Response
     */
    201: EmploymentTypeResponse;
};

export type CreateEmploymentTypeApiV1EmploymentTypesPostResponse = CreateEmploymentTypeApiV1EmploymentTypesPostResponses[keyof CreateEmploymentTypeApiV1EmploymentTypesPostResponses];

export type DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Type Id
         */
        type_id: string;
    };
    query?: never;
    url: '/api/v1/employment-types/{type_id}';
};

export type DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteError = DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteErrors[keyof DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteErrors];

export type DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteResponse = DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteResponses[keyof DeleteEmploymentTypeApiV1EmploymentTypesTypeIdDeleteResponses];

export type ListGradesApiV1GradesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/grades';
};

export type ListGradesApiV1GradesGetResponses = {
    /**
     * Response List Grades Api V1 Grades Get
     *
     * Successful Response
     */
    200: Array<GradeResponse>;
};

export type ListGradesApiV1GradesGetResponse = ListGradesApiV1GradesGetResponses[keyof ListGradesApiV1GradesGetResponses];

export type CreateGradeApiV1GradesPostData = {
    body: GradeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/grades';
};

export type CreateGradeApiV1GradesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGradeApiV1GradesPostError = CreateGradeApiV1GradesPostErrors[keyof CreateGradeApiV1GradesPostErrors];

export type CreateGradeApiV1GradesPostResponses = {
    /**
     * Successful Response
     */
    201: GradeResponse;
};

export type CreateGradeApiV1GradesPostResponse = CreateGradeApiV1GradesPostResponses[keyof CreateGradeApiV1GradesPostResponses];

export type ReorderGradesApiV1GradesOrderPatchData = {
    body: GradeReorder;
    path?: never;
    query?: never;
    url: '/api/v1/grades/order';
};

export type ReorderGradesApiV1GradesOrderPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderGradesApiV1GradesOrderPatchError = ReorderGradesApiV1GradesOrderPatchErrors[keyof ReorderGradesApiV1GradesOrderPatchErrors];

export type ReorderGradesApiV1GradesOrderPatchResponses = {
    /**
     * Response Reorder Grades Api V1 Grades Order Patch
     *
     * Successful Response
     */
    200: Array<GradeResponse>;
};

export type ReorderGradesApiV1GradesOrderPatchResponse = ReorderGradesApiV1GradesOrderPatchResponses[keyof ReorderGradesApiV1GradesOrderPatchResponses];

export type DeleteGradeApiV1GradesGradeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Grade Id
         */
        grade_id: string;
    };
    query?: never;
    url: '/api/v1/grades/{grade_id}';
};

export type DeleteGradeApiV1GradesGradeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGradeApiV1GradesGradeIdDeleteError = DeleteGradeApiV1GradesGradeIdDeleteErrors[keyof DeleteGradeApiV1GradesGradeIdDeleteErrors];

export type DeleteGradeApiV1GradesGradeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGradeApiV1GradesGradeIdDeleteResponse = DeleteGradeApiV1GradesGradeIdDeleteResponses[keyof DeleteGradeApiV1GradesGradeIdDeleteResponses];

export type UpdateGradeApiV1GradesGradeIdPatchData = {
    body: GradeUpdate;
    path: {
        /**
         * Grade Id
         */
        grade_id: string;
    };
    query?: never;
    url: '/api/v1/grades/{grade_id}';
};

export type UpdateGradeApiV1GradesGradeIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGradeApiV1GradesGradeIdPatchError = UpdateGradeApiV1GradesGradeIdPatchErrors[keyof UpdateGradeApiV1GradesGradeIdPatchErrors];

export type UpdateGradeApiV1GradesGradeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GradeResponse;
};

export type UpdateGradeApiV1GradesGradeIdPatchResponse = UpdateGradeApiV1GradesGradeIdPatchResponses[keyof UpdateGradeApiV1GradesGradeIdPatchResponses];
